[project]
name = "gemini-paper-summarizer"
version = "0.1.0"
description = "Gemini Paper Summarizer"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "google-generativeai>=0.8.3",
    "python-dotenv>=1.0.1",
]
